import type { LayoutSettings } from '@/lib/types';

export type LayoutPreset = LayoutSettings & { description: string; tags: string[] };

export const layoutPresets: LayoutPreset[] = [
  {
    id: 'classic-topnav',
    title: 'Classic Top Nav',
    description: 'Balanced, familiar layout with a sticky top navigation.',
    tags: ['classic', 'balanced', 'sticky'],
    sectionOrder: ['hero','about','skills','experience','education','projects','contact'],
    container: 'normal',
    navStyle: 'sticky',
    cardStyle: 'bordered',
    radius: 'lg',
    shadow: 'soft',
    projectLayout: 'grid',
  imageShape: 'circle',
    sectionSeparators: 'none',
    spacingScale: 'comfortable',
    typographyScale: 'normal',
  },
  {
    id: 'sidebar-modern',
    title: 'Modern Sidebar',
    description: 'Left sidebar navigation with vertical section highlights.',
    tags: ['modern', 'sidebar', 'pro'],
    sectionOrder: ['hero','about','skills','projects','experience','education','contact'],
    container: 'wide',
    navStyle: 'sidebar',
    cardStyle: 'solid',
    radius: 'md',
    shadow: 'elevated',
    projectLayout: 'masonry',
  imageShape: 'circle',
    sectionSeparators: 'angled',
    spacingScale: 'comfortable',
    typographyScale: 'normal',
  },
  {
    id: 'glassmorphic-elegance',
    title: 'Glassmorphic Elegance',
    description: 'Glass cards, soft shadows, and generous whitespace.',
    tags: ['glass', 'elegant', 'spacious'],
    sectionOrder: ['hero','about','projects','skills','experience','education','contact'],
    container: 'wide',
    navStyle: 'top',
    cardStyle: 'glass',
    radius: 'xl',
    shadow: 'soft',
    projectLayout: 'grid',
  imageShape: 'circle',
    sectionSeparators: 'wave',
    spacingScale: 'comfortable',
    typographyScale: 'larger',
  },
  {
    id: 'editorial-serif',
    title: 'Editorial Serif',
    description: 'Magazine-inspired with larger typography and serif headings.',
    tags: ['editorial', 'serif', 'large-type'],
    sectionOrder: ['hero','about','experience','education','projects','skills','contact'],
    container: 'narrow',
    navStyle: 'top',
    cardStyle: 'bordered',
    radius: 'lg',
    shadow: 'none',
    projectLayout: 'grid',
  imageShape: 'circle',
    sectionSeparators: 'none',
    spacingScale: 'cozy',
    typographyScale: 'editorial',
  },
  {
    id: 'bold-grid',
    title: 'Bold Grid',
    description: 'Strong grid rhythm, assertive spacing, and bold cards.',
    tags: ['grid', 'bold', 'pro'],
    sectionOrder: ['hero','skills','projects','about','experience','education','contact'],
    container: 'full',
    navStyle: 'sticky',
    cardStyle: 'solid',
    radius: 'md',
    shadow: 'elevated',
    projectLayout: 'grid',
  imageShape: 'circle',
    sectionSeparators: 'angled',
    spacingScale: 'comfortable',
    typographyScale: 'larger',
  },
  {
    id: 'minimal-flow',
    title: 'Minimal Flow',
    description: 'Ultra-clean linear flow with compact spacing and simple cards.',
    tags: ['minimal', 'clean', 'fast'],
    sectionOrder: ['hero','about','skills','experience','education','projects','contact'],
    container: 'narrow',
    navStyle: 'top',
    cardStyle: 'bordered',
    radius: 'sm',
    shadow: 'none',
    projectLayout: 'grid',
  imageShape: 'circle',
    sectionSeparators: 'none',
    spacingScale: 'compact',
    typographyScale: 'normal',
  },
  {
    id: 'showcase-carousel',
    title: 'Showcase Carousel',
    description: 'Project-first with carousel showcase front and center.',
    tags: ['showcase', 'carousel', 'visual'],
    sectionOrder: ['hero','projects','about','skills','experience','education','contact'],
    container: 'wide',
    navStyle: 'top',
    cardStyle: 'solid',
    radius: 'lg',
    shadow: 'soft',
    projectLayout: 'carousel',
  imageShape: 'circle',
    sectionSeparators: 'wave',
    spacingScale: 'comfortable',
    typographyScale: 'normal',
  },
  {
    id: 'techy-sidebar',
    title: 'Techy Sidebar',
    description: 'Developer-focused sidebar with code-like accent styling.',
    tags: ['tech', 'sidebar', 'dev'],
    sectionOrder: ['hero','skills','projects','about','experience','education','contact'],
    container: 'normal',
    navStyle: 'sidebar',
    cardStyle: 'bordered',
    radius: 'md',
    shadow: 'soft',
    projectLayout: 'masonry',
  imageShape: 'circle',
    sectionSeparators: 'angled',
    spacingScale: 'cozy',
    typographyScale: 'normal',
  },
  {
    id: 'creative-wave',
    title: 'Creative Wave',
    description: 'Playful wave separators and dynamic visual rhythm.',
    tags: ['creative', 'wave', 'playful'],
    sectionOrder: ['hero','about','projects','skills','experience','education','contact'],
    container: 'wide',
    navStyle: 'top',
    cardStyle: 'glass',
    radius: 'xl',
    shadow: 'soft',
    projectLayout: 'grid',
  imageShape: 'circle',
    sectionSeparators: 'wave',
    spacingScale: 'comfortable',
    typographyScale: 'larger',
  },
  {
    id: 'brutalist-stack',
    title: 'Brutalist Stack',
    description: 'Hard edges, big type, stacked sections with strong contrast.',
    tags: ['brutalist', 'bold', 'stack'],
    sectionOrder: ['hero','about','skills','projects','experience','education','contact'],
    container: 'full',
    navStyle: 'sticky',
    cardStyle: 'solid',
    radius: 'sm',
    shadow: 'elevated',
    projectLayout: 'grid',
  imageShape: 'circle',
    sectionSeparators: 'angled',
    spacingScale: 'comfortable',
    typographyScale: 'larger',
  },
];

export default layoutPresets;
